views/dashboard.py
import os
import uuid

from datetime import datetime

from pathlib import Path
from flask import Blueprint, render_template, redirect, request, session, flash
from flask_login import login_required
from models import MLProject, MLProjectConfig
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc

from werkzeug.utils import secure_filename

basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def generate_id():
    return uuid.uuid4().hex


dashboard_blueprint = Blueprint('dashboard', __name__)

db = SQLAlchemy()


@dashboard_blueprint.route("/")
def index():
    """
    Home page
    """
    if session.get('_user_id', None):
        flash('Welcome to Interactive ML Pipeline.', 'success')
        return redirect('/dashboard/home')
    return render_template('index.html', page_index=True)


@dashboard_blueprint.route("/dashboard/explore")
@login_required
def explore():
    """
    Explore page
    """
    return render_template('dashboard/explore.html', page_index=True)


@dashboard_blueprint.route("/dashboard/home")
@login_required
def dashboard():
    res = db.session.query(MLProject).filter_by(created_by=session['_user_id']).order_by(
        desc(MLProject.created_at)).all()
    counts = {
        "draft": db.session.query(MLProject).filter_by(created_by=session['_user_id'], status='Draft').count(),
        "completed": db.session.query(MLProject).filter_by(created_by=session['_user_id'], status='Completed').count(),
        "in_progress": db.session.query(MLProject).filter_by(created_by=session['_user_id'], status='In Progress').count(),
    }
    return render_template(
        'dashboard/home.html',
        active_dashboard="home",
        counts=counts,
        projects=res)


@dashboard_blueprint.route('/<int:id>/edit-project', methods=['GET', 'POST'])
@login_required
def dashboard_edit_project(id):
    project = db.session.query(MLProject).get(id)
    if request.method == 'POST':
        project.title = request.form.get('title', None)
        project.description = request.form.get('description', None)
        project.status = request.form.get('btnradio', None)
        db.session.commit()
        db.session.close()
        flash('Successfully edited your project.', 'success')
        return redirect('/dashboard/home')
    return render_template(
        'dashboard/upload.html',
        active_dashboard="upload",
        edit=True,
        project=project)


@dashboard_blueprint.route("/dashboard/upload", methods=["POST", "GET"])
@login_required
def dashboard_upload():
    """
    Dashboard upload dataset
    """
    if request.method == 'POST':
        title = request.form.get('title', None)
        description = request.form.get('description', None)
        status = request.form.get('btnradio', None)
        file = request.files['file']
        if file and file.mimetype != 'text/csv':
            flash('Please upload csv datasets only.', 'danger')
            return render_template('dashboard/upload.html', active_dashboard="upload")
        if not all([title, description, file]):
            flash('Please complete all fields including dataset.', 'danger')
            return render_template('dashboard/upload.html', active_dashboard="upload")

        secure_file_name = secure_filename(file.filename)  # to make the directory
        original_file_name = secure_file_name.replace('.', '_original.')

        current_user = session['twitter_oauth_token']['screen_name']
        dataset_url = f"static/uploads/datasets/{current_user}/{secure_file_name.split('.')[0]}"

        Path(basedir, dataset_url).mkdir(parents=True, exist_ok=True)

        file.save(os.path.join(basedir, dataset_url, original_file_name))
        ml_project = MLProject(
            created_at=datetime.now(),
            created_by=session['_user_id'],
            title=title,
            description=description,
            filename=original_file_name,
            filename_preferred=secure_file_name.split('.')[0], # directory name
            status=status)
        db.session.add(ml_project)
        db.session.commit()
        ml_project_config = MLProjectConfig(
            created_at=datetime.now(),
            ml_project=ml_project.id,
            config={},
            description='')
        db.session.add(ml_project_config)
        db.session.commit()
        db.session.close()
        flash('Successfully created your project.', 'success')
        return redirect('/dashboard/home')
    return render_template('dashboard/upload.html', active_dashboard="upload")


@dashboard_blueprint.route("/dashboard/history")
@login_required
def dashboard_history():
    res = db.session.query(MLProject).filter_by(created_by=session['_user_id']).order_by(
        desc(MLProject.created_at)).all()
    return render_template(
        'dashboard/history.html',
        history=res,
        active_dashboard="history")

views/pipeline.py
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from datetime import datetime
from pathlib import Path
from flask import Blueprint, render_template, redirect, request, session, abort, url_for, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import login_required
from sqlalchemy.orm.attributes import flag_modified

from models import MLProject, MLProjectConfig

# ML models
from sklearn.linear_model import LinearRegression, Ridge, Lasso, BayesianRidge
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier

from sqlalchemy.exc import NoResultFound

import seaborn as sns
import matplotlib
matplotlib.use('Agg')

pipeline_blueprint = Blueprint('pipeline', __name__)

db = SQLAlchemy()
basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@pipeline_blueprint.route('/', methods=['GET'])
def pipeline_demo():
    return render_template('pipeline/workflow.html')


def get_project_user_df(id):
    """
    GET logged in user from session, project from url id and the original dataframe
    """
    try:
        current_user = session['twitter_oauth_token']['screen_name']
        project = db.session.query(MLProject).get(id)
        config = db.session.query(MLProjectConfig).filter(
            MLProjectConfig.ml_project == id).one()
    except NoResultFound:
        abort(404)
    db.session.close()
    # READ original
    df = pd.read_csv(os.path.join(
        basedir, f'static/uploads/datasets/{current_user}/{project.filename_preferred}', project.filename))
    return current_user, project, config, df


@pipeline_blueprint.route('<int:id>/cleaning', methods=['GET'])
@login_required
def pipeline_detail_cleaning(id):
    """
    DETAIL CLEANING PAGE
    """
    current_user, project, config, df = get_project_user_df(id)

    # READ cleaned
    df_cleaned = None
    df_cleaned_head = None
    df_cleaned_shape = None
    try:
        cleaned_url = os.path.join(
            basedir, f'static/uploads/datasets/{current_user}/{project.filename_preferred}', project.filename.replace('_original', '_cleaned'))
        df_cleaned = pd.read_csv(cleaned_url)
        df_cleaned_head = df_cleaned.head().to_html(
            classes=('table table-hover dataset-table'))
        df_cleaned_shape = df_cleaned.shape
    except Exception as e:
        print(e)

    df_original_head = df.head()

    # report null values
    null_values = df.isnull().sum().to_dict()
    null_values_cleaned = df_cleaned.isnull().sum(
    ).to_dict() if df_cleaned is not None else {}

    return render_template(
        'pipeline/data-cleaning.html',
        project=project,
        dataset=df_original_head.to_html(
            classes=('table table-hover dataset-table')),
        columns=df_original_head.columns.to_list(),
        progress=16.66,
        active_pipeline='cleaning',
        all_df=df.to_html(classes=('table table-hover dataset-table')),
        shape=df.shape,
        null_values=null_values,
        df_cleaned_head=df_cleaned_head,
        df_cleaned_shape=df_cleaned_shape,
        cleaned_null_values=null_values_cleaned,
        project_config=config)


@pipeline_blueprint.route('<int:id>/cleaning/perform-cleanup', methods=['POST'])
@login_required
def pipeline_perform_cleaning(id):
    """
    PROCESS CLEANING
    """
    project = db.session.query(MLProject).get(id)
    current_user = session['twitter_oauth_token']['screen_name']
    project_config = db.session.query(MLProjectConfig).filter(
        MLProjectConfig.ml_project == id).one()
    # READ original
    df = pd.read_csv(os.path.join(
        basedir, f'static/uploads/datasets/{current_user}/{project.filename_preferred}',
        project.filename))
    filtered_columns = request.form.getlist('filtered_columns')
    original_columns_len = len(df.columns.to_list())
    if original_columns_len - len(filtered_columns) <= 1:
        db.session.commit()
        flash('Please keep at least two columns in the dataset.', 'danger')
        return redirect(url_for('pipeline.pipeline_detail_cleaning', id=id))
    null_values = request.form.get('null_values', None, type=int)
    cleaning_config = {'cleaning': {
        'fields': filtered_columns, 'nan': null_values}}
    project_config.config = cleaning_config
    db.session.commit()

    if null_values == 1:
        df.fillna(df.mean(), inplace=True)
    elif null_values == 2:
        df.fillna(df.median(), inplace=True)
    elif null_values == 3:
        df.dropna(inplace=True)
    df.drop(columns=filtered_columns, inplace=True)
    df.columns = df.columns.str.replace(' ', '_')
    df.columns = df.columns.str.lower()

    df.to_csv(os.path.join(
        basedir, f'static/uploads/datasets/{current_user}/{project.filename_preferred}',
        project.filename.replace('_original', '_cleaned')), index=False)

    db.session.close()
    flash('Successfully cleaned data.', 'success')
    return redirect(url_for('pipeline.pipeline_detail_cleaning', id=id))


@pipeline_blueprint.route('<int:id>/eda', methods=['GET', 'POST'])
@login_required
def pipeline_detail_eda(id):
    """
    Exploratory Data Analysis
    """
    current_user, project, config, all_df = get_project_user_df(id)
    dataset_summary = True
    hist_plot = False
    correlation = False
    pairplot = False
    boxplot = False
    hist_col = ''
    plot_url = ''
    if request.method == "POST":
        active_vis = request.form.get('visualization', None)
        dataset_summary = True if active_vis == 'summary' else False
        hist_plot = True if active_vis == 'histogram' else False
        correlation = True if active_vis == 'correlation' else False
        pairplot = True if active_vis == 'pairplot' else False
        boxplot = True if active_vis == 'boxplot' else False
        if hist_plot and not request.form.get('hist_col'):
            db.session.close()
            flash('Please select columns for histogram distribution.', 'danger')
            return redirect(url_for('pipeline.pipeline_detail_eda', id=id))
        hist_col = request.form.get('hist_col')

    if not project:
        abort(404)

    try:
        cleaned_url = os.path.join(
            basedir, f'static/uploads/datasets/{current_user}/{project.filename_preferred}', project.filename.replace('_original', '_cleaned'))
        df = pd.read_csv(cleaned_url)
    except FileNotFoundError:
        db.session.close()
        flash('Please clean the dataset to continue.', 'danger')
        return redirect(url_for('pipeline.pipeline_detail_cleaning', id=id))

    head = df.head()
    summary = df.describe()

    if hist_plot:
        sns.displot(df[hist_col])
        plt.title(f'{hist_col} Distribution')
        plot_url = f"static/uploads/plots/{current_user}"
        Path(basedir, plot_url).mkdir(parents=True, exist_ok=True)
        plt.savefig(os.path.join(basedir, plot_url, 'hist.png'),
                    dpi=300, bbox_inches='tight', pad_inches=0.3)
        plot_url = f"uploads/plots/{current_user}/hist.png"
        flash('Successfully generated histogram.', 'success')
    else:
        hist_col = None

    if correlation:
        plt.figure(figsize=(10, 10))
        sns.heatmap(df.corr(), annot=True, cmap="Blues")
        plot_url = f"static/uploads/plots/{current_user}"
        Path(basedir, plot_url).mkdir(parents=True, exist_ok=True)
        plt.savefig(os.path.join(basedir, plot_url, 'correlation.png'),
                    dpi=300, bbox_inches='tight', pad_inches=0.2)
        plot_url = f"uploads/plots/{current_user}/correlation.png"
        flash('Successfully generated correlation.', 'success')

    if pairplot:
        sns.pairplot(df.iloc[:,0:4], height=2.5)
        plt.tight_layout()
        plot_url = f"static/uploads/plots/{current_user}"
        Path(basedir, plot_url).mkdir(parents=True, exist_ok=True)
        plt.savefig(os.path.join(basedir, plot_url, 'pairplot.png'),
                    dpi=300, bbox_inches='tight', pad_inches=0.2)
        plot_url = f"uploads/plots/{current_user}/pairplot.png"
        flash('Successfully generated pairplot.', 'success')

    if boxplot:
        plt.figure().clear()
        sns.boxplot(data=df.iloc[:, 0:4])
        plot_url = f"static/uploads/plots/{current_user}"
        Path(basedir, plot_url).mkdir(parents=True, exist_ok=True)
        plt.savefig(os.path.join(basedir, plot_url, 'boxplot.png'),
                    dpi=300, bbox_inches='tight', pad_inches=0.2)
        plot_url = f"uploads/plots/{current_user}/boxplot.png"
        flash('Successfully generated boxplot.', 'success')

    return render_template(
        'pipeline/eda.html',
        project=project,
        dataset=head.to_html(classes=('table table-hover dataset-table')),
        columns=head.columns.to_list(),
        active_pipeline='eda',
        summary=summary.to_html(classes=('table table-hover dataset-table')),
        progress=33.32,
        dataset_summary=dataset_summary,
        hist_summary=hist_plot,
        correlation=correlation,
        pairplot=pairplot,
        boxplot=boxplot,
        plot_url=plot_url,
        hist_col=hist_col,
        shape=df.shape,
        all_df=all_df.to_html(classes=('table table-hover dataset-table')),
    )


@pipeline_blueprint.route('<int:id>/scaling', methods=['GET', 'POST'])
@login_required
def pipeline_detail_scaling(id):
    """
    APPLY different scaler to the cleaned dataset
    """
    current_user, project, config, all_df = get_project_user_df(id)

templates/pipeline/data-scaling.html
{% extends "pipeline/pipeline_base.html" %}
{% block pipeline_content %}
<div class="card">
  <div class="card-header">
    <h5>Data Scaling</h5>
    <small class="text-muted">In this phase you can perform data scaling as scaling of the data makes it easy for a model to learn and understand the problem.</small>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-9">
        <div class="table-responsive">
          {{ scaled_dataset|safe }}
        </div>
      </div>
      <div class="col-md-3">
        <h5>Choose Scaler</h5>
        <hr>
        <form action="{{ url_for('pipeline.pipeline_detail_scaling', id=project.id) }}" method="POST">
          <div class="alert alert-success">
            Applied Scaling: {{ required_scaler }}
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="scaler" value="minmax" id="scaler_minmax" {% if required_scaler == 'minmax' %}checked{% endif %}>
            <label class="form-check-label" for="scaler_minmax">
              MinMax Scaler
              <small class="d-block">If you are transforming a feature, its non distorting</small>
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="scaler" value="robust" id="scaler_robust" {% if required_scaler == 'robust' %}checked{% endif %}>
            <label class="form-check-label" for="scaler_robust">
              Robust Scaler
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="scaler" value="standard" id="scaler_standard" {% if required_scaler == 'standard' %}checked{% endif %}>
            <label class="form-check-label" for="scaler_standard">
              Standard Scaler
              <small class="d-block">all features will have mean of 0 and SD of 1</small>
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="reset_scaling" id="reset_scaling">
            <label class="form-check-label" for="reset_scaling">
              Reset Scaling
              <small class="d-block">Revert any scaling applied</small>
            </label>
          </div>
          <hr>
          <button type="submit" class="btn btn-sm btn-primary">Apply Scaling</button>
        </form>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="d-flex justify-content-between">
      <a href="{{ url_for('pipeline.pipeline_detail_eda', id=project.id) }}" class="btn btn-secondary btn-sm" disabled><i class="icon bi-arrow-left-circle mx-1"></i>Previous</a>
      <a href="{{ url_for('pipeline.pipeline_detail_train_test', id=project.id) }}" class="btn btn-success btn-sm text-white">Next<i class="icon bi-arrow-right-circle mx-1"></i></a>
    </div>
  </div>
</div>
{% endblock pipeline_content %}

templates/pipeline/eda.html
{% extends "pipeline/pipeline_base.html" %}
{% block pipeline_content %}
<div class="card">
  <div class="card-header">
    <h5>Exploratory Data Analysis and Visualization</h5>
    <small class="text-muted">In this phase you can visualize heatmaps and other visualization based
      on the dataset you've cleaned.</small>
  </div>
  <div class="card-body">

    <div class="row">
      <div class="col-md-9">
        <h5>Dataset Summary</h5>
        {% if dataset_summary %}
        <div class="table-responsive">
          {{ summary|safe }}
        </div>
        {% elif hist_summary %}
        <div>
          <img src="{{ url_for('static', filename=plot_url) }}" height="600" width="600" style="margin: 0 auto; display: block;">
        </div>
        {% elif correlation %}
          <img src="{{ url_for('static', filename=plot_url) }}" height="900" width="100%" style="margin: 0 auto; display: block; object-fit: contain;">
        {% elif pairplot %}
          <img src="{{ url_for('static', filename=plot_url) }}" height="700" width="700" style="margin: 0 auto; display: block;">
        {% elif boxplot %}
          <img src="{{ url_for('static', filename=plot_url) }}" height="700" width="700" style="margin: 0 auto; display: block;">
        {% endif %}
      </div>
      <div class="col-md-3">
        <h5>Choose Visualization to Generate</h5>
        <hr>
        <form method="POST" action="{{ url_for('pipeline.pipeline_detail_eda', id=project.id) }}">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="visualization" value="summary" id="id_summary" {% if dataset_summary %}checked{% endif %}>
            <label class="form-check-label" for="id_summary">
              Dataset Summary
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="visualization" value="histogram" id="id_histogram" {% if hist_summary %}checked{% endif %}>
            <label class="form-check-label" for="id_histogram">
              Histogram
              <div class="ml-4">
                {% for col in columns %}
                  <div class="form-check form-check-inline">
                    <input class="form-check-input custom" type="radio" name="hist_col" value="{{ col }}" id="id_{{ col }}" {% if col == hist_col %} checked {% endif %}>
                    <label class="form-check-label" for="id_{{ col }}">{{ col }}</label>
                  </div>
                {% endfor %}
              </div>
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="visualization" value="correlation" id="id_correlation" {% if correlation %}checked{% endif %}>
            <label class="form-check-label" for="id_correlation">
              Correlation
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="visualization" value="pairplot" id="id_pairplot" {% if pairplot %}checked{% endif %}>
            <label class="form-check-label" for="id_pairplot">
              Pairplot
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="visualization" value="boxplot" id="id_boxplot" {% if boxplot %}checked{% endif %}>
            <label class="form-check-label" for="id_boxplot">
              Boxplot
            </label>
          </div>
          <hr>
          <button type="submit" class="btn btn-primary btn-sm">Apply Changes</button>
        </form>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="d-flex justify-content-between">
      <a href="{{ url_for('pipeline.pipeline_detail_cleaning', id=project.id) }}" class="btn btn-secondary btn-sm" disabled>
        <i class="icon bi-arrow-left-circle mx-1"></i>Previous</a>
      <a href="{{ url_for('pipeline.pipeline_detail_scaling', id=project.id) }}" class="btn btn-success btn-sm text-white">
        Next<i class="icon bi-arrow-right-circle mx-1"></i></a>
    </div>
  </div>
</div>
{% endblock pipeline_content %}

templates/pipeline/pipeline_base.html
{% extends "base.html" %}
{% block title %} Pipeline{% endblock title %}
{% block content %}
<div class="container">
  <div class="row my-4">
    <div class="col-md-12 mb-3">
      <h5>Dataset Title: {{ project.title }} <span class="badge bg-warning">{{ project.status }}</span></h5>
      <p class="text-muted">{{ project.description }}</p>
      <div>
        <a href="{{ url_for('dashboard.dashboard_edit_project', id=project.id) }}"><button class="btn btn-outline-success btn-sm">Edit</button></a>
        <button class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#modalDelete">Delete</button>
        <button class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#modalPreviewDataset">Preview All Dataset</button>
      </div>
    </div>
    <div class="col-md-12">
      <div class="d-flex justify-content-around mb-3">
        <div>
          <i class="icon pipeline-nav-icon bi-magic"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'cleaning' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_cleaning', id=project.id) }}">Data Cleaning</a>
        </div>
        <hr aria-orientation="horizontal" class="flex-grow-1 mx-2"/>
        <div>
          <i class="icon pipeline-nav-icon bi-pie-chart"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'eda' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_eda', id=project.id) }}">EDA</a>
        </div>
        <hr aria-orientation="horizontal" class="flex-grow-1 mx-2"/>
        <div>
          <i class="icon pipeline-nav-icon bi-gear"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'scaling' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_scaling', id=project.id) }}">Data Scaling</a>
        </div>
        <hr aria-orientation="horizontal" class="flex-grow-1 mx-2"/>
        <div>
          <i class="icon pipeline-nav-icon bi-layers-half"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'train-test' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_train_test', id=project.id) }}">Train Test Split</a>
        </div>
        <hr aria-orientation="horizontal" class="flex-grow-1 mx-2"/>
        <div>
          <i class="icon pipeline-nav-icon bi-window-stack"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'features' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_features', id=project.id) }}">Feature Engineering</a>
        </div>
        <hr aria-orientation="horizontal" class="flex-grow-1 mx-2"/>
        <div>
          <i class="icon pipeline-nav-icon bi-wrench-adjustable"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'train' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_train', id=project.id) }}">Train Models</a>
        </div>
        <hr aria-orientation="horizontal" class="flex-grow-1 mx-2"/>
        <div>
          <i class="icon pipeline-nav-icon bi-puzzle"></i>
          <a class="pipeline-nav-link {% if active_pipeline == 'predict' %}active{% endif %}" href="{{ url_for('pipeline.pipeline_detail_predict', id=project.id) }}">Predict</a>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="progress mb-3">
        <div class="progress-bar progress-bar-striped progress-bar-animated"
          role="progressbar"
          aria-valuenow="{{ progress }}"
          aria-valuemin="0"
          aria-valuemax="100"
          style="width: {{ progress }}%">
        </div>
      </div>
    </div>
    <div class="col-md-12">
      {% block pipeline_content %}{% endblock pipeline_content %}
    </div>
  </div>
  <div class="row my-4">
    <div class="col-md-12">
    </div>
  </div>
  <div class="row my-4">
    <div class="col-md-12">
    </div>
  </div>
  <div class="row my-4">
  </div>
  <div class="modal modal-xl" id="modalPreviewDataset" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <form>
          <div class="modal-header">
            <h5 class="modal-title">Preview Dataset</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="table-responsive">
              {{ all_df|safe }}
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="modal" id="modalDelete" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <form method="POST" action="/pipeline/delete">
          <div class="modal-header">
            <h5 class="modal-title">Confirm Deletion</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this dataset you're working on?</p>
            <input name="id" value="{{ project.id }}" hidden>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}