views/dashboard.py
import os
import uuid

from datetime import datetime

from pathlib import Path
from flask import Blueprint, render_template, redirect, request, session, flash
from flask_login import login_required
from models import MLProject, MLProjectConfig
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc

from werkzeug.utils import secure_filename

basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def generate_id():
    return uuid.uuid4().hex


dashboard_blueprint = Blueprint('dashboard', __name__)

db = SQLAlchemy()


@dashboard_blueprint.route("/")
def index():
    """
    Home page
    """
    if session.get('_user_id', None):
        flash('Welcome to Interactive ML Pipeline.', 'success')
        return redirect('/dashboard/home')
    return render_template('index.html', page_index=True)


@dashboard_blueprint.route("/dashboard/explore")
@login_required
def explore():
    """
    Explore page
    """
    return render_template('dashboard/explore.html', page_index=True)


@dashboard_blueprint.route("/dashboard/home")
@login_required
def dashboard():
    res = db.session.query(MLProject).filter_by(created_by=session['_user_id']).order_by(
        desc(MLProject.created_at)).all()
    counts = {
        "draft": db.session.query(MLProject).filter_by(created_by=session['_user_id'], status='Draft').count(),
        "completed": db.session.query(MLProject).filter_by(created_by=session['_user_id'], status='Completed').count(),
        "in_progress": db.session.query(MLProject).filter_by(created_by=session['_user_id'], status='In Progress').count(),
    }
    return render_template(
        'dashboard/home.html',
        active_dashboard="home",
        counts=counts,
        projects=res)


@dashboard_blueprint.route('/<int:id>/edit-project', methods=['GET', 'POST'])
@login_required
def dashboard_edit_project(id):
    project = db.session.query(MLProject).get(id)
    if request.method == 'POST':
        project.title = request.form.get('title', None)
        project.description = request.form.get('description', None)
        project.status = request.form.get('btnradio', None)
        db.session.commit()
        db.session.close()
        flash('Successfully edited your project.', 'success')
        return redirect('/dashboard/home')
    return render_template(
        'dashboard/upload.html',
        active_dashboard="upload",
        edit=True,
        project=project)


@dashboard_blueprint.route("/dashboard/upload", methods=["POST", "GET"])
@login_required
def dashboard_upload():
    """
    Dashboard upload dataset
    """
    if request.method == 'POST':
        title = request.form.get('title', None)
        description = request.form.get('description', None)
        status = request.form.get('btnradio', None)
        file = request.files['file']
        if file and file.mimetype != 'text/csv':
            flash('Please upload csv datasets only.', 'danger')
            return render_template('dashboard/upload.html', active_dashboard="upload")
        if not all([title, description, file]):
            flash('Please complete all fields including dataset.', 'danger')
            return render_template('dashboard/upload.html', active_dashboard="upload")

        secure_file_name = secure_filename(file.filename)  # to make the directory
        original_file_name = secure_file_name.replace('.', '_original.')

        current_user = session['twitter_oauth_token']['screen_name']
        dataset_url = f"static/uploads/datasets/{current_user}/{secure_file_name.split('.')[0]}"

        Path(basedir, dataset_url).mkdir(parents=True, exist_ok=True)

        file.save(os.path.join(basedir, dataset_url, original_file_name))
        ml_project = MLProject(
            created_at=datetime.now(),
            created_by=session['_user_id'],
            title=title,
            description=description,
            filename=original_file_name,
            filename_preferred=secure_file_name.split('.')[0], # directory name
            status=status)
        db.session.add(ml_project)
        db.session.commit()
        ml_project_config = MLProjectConfig(
            created_at=datetime.now(),
            ml_project=ml_project.id,
            config={},
            description='')
        db.session.add(ml_project_config)
        db.session.commit()
        db.session.close()
        flash('Successfully created your project.', 'success')
        return redirect('/dashboard/home')
    return render_template('dashboard/upload.html', active_dashboard="upload")


@dashboard_blueprint.route("/dashboard/history")
@login_required
def dashboard_history():
    res = db.session.query(MLProject).filter_by(created_by=session['_user_id']).order_by(
        desc(MLProject.created_at)).all()
    return render_template(
        'dashboard/history.html',
        history=res,
        active_dashboard="history")

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}- ML Pipeline</title>
    <link href="{{ url_for('static', filename='dist/main.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script defer="" src="{{ url_for('static', filename='dist/main.js') }}"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container">
        <a class="navbar-brand" href="/">
          <img src="{{ url_for('static', filename='images/logo3.png') }}" height="40"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('dashboard.dashboard') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/dashboard/home">Dashboard</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Explore Datasets
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="https://archive.ics.uci.edu/ml/datasets.php">UCI</a></li>
                <li><a class="dropdown-item" href="https://www.kaggle.com/datasets">Kaggle</a></li>
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav">
            {% if page_index %}
              <li class="nav-item">
                <a class="nav-link" href="/pipeline">IMLP Example</a>
              </li>
            {% endif %}

            {% if current_user.is_authenticated %}
              <li class="nav-item">
                <em>{{ current_user.username }}</em>
                <img src="https://cdn-icons-png.flaticon.com/512/124/124021.png" class="rounded-circle"
                  style="width: 40px;" alt="{{ current_user.username }}" />
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
            -->
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div style="position: fixed; bottom: 10px; z-index: 99; right: 50px; width: 350px;" class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
              <span class="text-capitalize font-weight-bold">
                {% if category == 'danger' %}<i class="icon bi-exclamation-triangle-fill mr-3"></i>{% else %}<i class="icon bi-check-circle-fill mr-3"></i>{% endif %}
              </span> {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock %}
    </div>
    <div class="footer">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-6 d-flex align-items-center mx-5">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="text-muted">© 2022 Interactive ML Pipeline. Created by: Simrik Rijal, Sisir Ghimire Chettri</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex mx-5">
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><i class="icon bi-twitter"></i></a></li>
        </ul>
      </footer>
    </div>
    <script>
      $(document).ready(function() {
        $(".alert").delay(4000).slideUp(200, function() {
          $(this).alert('close');
        });
      });
    </script>
    {% block js %}{% endblock js %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
  <div class="row" style="border: 1px solid #efefef; border-radius: 10px; margin: 32px 220px; padding: 10px;">
    <div class="col-md-6 text-center">
      <img src="{{ url_for('static', filename='images/interactive.png') }}" style="width: 100%"></i>
    </div>
    <div class="col-md-6">
      <h4 class="text-center">Welcome to Interactive Machine Learning Pipeline</h4>
      <hr>
      <small class="d-block">
       <i class="icon bi-check-circle-fill" style="color: green; font-size: 1.2rem;"></i>
       Upload your dataset and work on your Machine Learning pipeline interactively via web
       platform.
      </small>
      <small class="d-block my-4">
       <i class="icon bi-check-circle-fill" style="color: green; font-size: 1.2rem;"></i>
       Align your work as a data analysts to make your work finest in less time.
      </small>
      <small class="d-block">
       <i class="icon bi-check-circle-fill" style="color: green; font-size: 1.2rem;"></i>
       Students are able to understand ML pipeline better.
      </small>
      <small class="d-block my-4">
       <i class="icon bi-check-circle-fill" style="color: green; font-size: 1.2rem;"></i>
       We are team of students who are aiming for simplifying Machine Learning pipeline process.
      </small>
      <div class="text-center">
        {% if not current_user.is_authenticated %}
        <a href="/twitter" class="text-center">
          <button type="button" class="btn btn-primary my-1 btn-lg" style="background: #1E9BF0;
            border-color: white;"><i class="icon bi-twitter mx-3"></i>Login with Twitter</button>
        </a>
        {% else %}
        <a href="/logout" class="text-center">Logout</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}